version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: laravel_backend
    volumes:
      - ./backend:/var/www
    ports:
      - "9000:9000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: angular_frontend
    ports:
      - "4200:80"

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
